# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Siddhartha Jain
tagline:          'TCS Enthusiast'
description:      'Sophomore at <a href="http://iiitd.ac.in/" target="_blank">IIIT-Delhi</a>, studying Computer Science & Applied Mathematics. Founder & Coordinator of its <a href="http://bit.ly/EvaristeClub" target="_blank">Math Club</a>. Member of the <a href="http://studentsenate.iiitd.edu.in/" target="_blank">Student Senate</a>.'
url:              http://sidjain.me
baseurl:          /

author:
  name:           'Siddhartha Jain'
  url:            http://sidjain.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/siddjai/siddjai.github.io

#Default layouts
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
