remote-theme: sharu725/online-cv
title: Siddhartha Jain
description: While my love is primarily reserved for Theoretical Computer Science and Math, I have an interest in Writing fiction, Photography and Design.
