# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jain
tagline:          'TCS Enthusiast'
description:      Sophomore at IIIT-Delhi.
url:              http://sidjain.me
baseurl:          /

author:
  name:           'Siddhartha Jain'
  url:            sidjain.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/siddjai/siddjai.github.io
