# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SIDDHARTHA
tagline:          'CS&DM Researcher'
description:      'Visited <a href="http://itcs.shufe.edu.cn/" target="_blank">ITCS@SUFE</a> for summer. Undergrad at <a href="http://iiitd.ac.in/" target="_blank">IIIT-Delhi</a>, studying Computer Science & Mathematics. Founder of its <a href="http://bit.ly/EvaristeClub" target="_blank">Math Club</a>. <a href="Resume.pdf">Resume</a>.'
url:              http://sidjain.me
baseurl:          /

author:
  name:           'Siddhartha Jain'
  url:            http://sidjain.me

paginate:         10
paginate_path:    "/writing/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/siddjai/siddjai.github.io

#Default layouts
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
